### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by BobHarper1** [timpwbaker/digital-maturity-matrix#1]
It would be helpful to see question completion progress across the 8 (?) areas

**Comment by timpwbaker** [comment]
Thanks for the suggestion Bob. I agree this would be helpful. I'll get it implemented over the next few weeks.

**Comment by timpwbaker** [comment]
Hi @BobHarper1, sorry this has taken so long, had lots on, but I've added a progress bar, thanks again for your suggestion.

<img width="1104" alt="screen shot 2017-09-23 at 13 03 16" src="https://user-images.githubusercontent.com/8363245/30773035-148a2f66-a060-11e7-82dc-4208305c16d4.png">

TB
